name: sw6
services:
  shopware:
    build: ${REPO_DIR:-.}/shopware-dockerized
    ports:
      - "80:80"
    volumes:
      - sw6-shopware-data:/usr/share/nginx/html:rw
      - ./sw-environment:/usr/share/nginx/html/.env.prod.local:rw
    networks: [sw6-network]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      start_interval: 3s
      start_period: 5s
      interval: 1s
      timeout: 3s
      retries: 10
    depends_on:
      database:
        condition: service_healthy
      valkey:
        condition: service_healthy
      opensearch:
        condition: service_healthy
  valkey:
    image: valkey/valkey:alpine
    restart: always
    command: [ "--maxmemory-policy", "volatile-lru", "--save", "", "--appendonly", "no" ]
    networks: [sw6-network]
    healthcheck:
      test: [ "CMD-SHELL", "valkey-cli ping | grep PONG" ]
      start_interval: 3s
      start_period: 5s
      interval: 1s
      timeout: 3s
      retries: 10
  opensearch:
    image: opensearchproject/opensearch:latest
    restart: always
    environment:
      discovery.type: "single-node"
      plugins.security.audit.type: "none"
      plugins.security.ssl.http.enabled: "false"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "${OPENSEARCH_ADMIN_PASSWORD:-c3o_ZPHo!}"
    volumes:
      - sw6-opensearch-data:/usr/share/opensearch/data:rw
    networks: [sw6-network]
    logging:
      driver: "json-file"
      options:
        max-size: "32m"
        max-file: "3"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--user", "admin:${OPENSEARCH_ADMIN_PASSWORD:-c3o_ZPHo!}", "http://localhost:9200/_cat/health" ]
      start_interval: 5s
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10
  database:
    image: mariadb:lts
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    command:
      - --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
      - --log_bin_trust_function_creators=1
      - --default-time-zone=+00:00
      - --group_concat_max_len=320000
      - --max_allowed_packet=64M
      # support many connections
      - --max_connections=512
      - --thread_cache_size=64
      - --table_open_cache=4096
      - --table_definition_cache=2048
      # thread-safe buffer scaling
      - --join_buffer_size=2M
      - --sort_buffer_size=2M
      - --read_buffer_size=1M
      - --read_rnd_buffer_size=2M
      # storage engine optimization
      - --innodb_buffer_pool_size=2048M
      - --innodb_buffer_pool_instances=2
      - --innodb_log_file_size=1024M
      - --innodb_log_buffer_size=64M
      # concurrent write optimization
      - --innodb_flush_log_at_trx_commit=2
      - --innodb_flush_method=O_DIRECT
      - --innodb_io_capacity=1536
      - --innodb_io_capacity_max=3072
      - --innodb_read_io_threads=8
      - --innodb_write_io_threads=8
    deploy:
      resources:
        limits:
          cpus: '2.0'
    volumes:
      - sw6-database-data:/var/lib/mysql:rw
    networks: [sw6-network]
    healthcheck:
      test: [ "CMD", "mariadb-admin" ,"ping", "-h", "localhost", "-p${DB_PASSWORD:-password}" ]
      start_interval: 3s
      start_period: 10s
      interval: 5s
      timeout: 1s
      retries: 10
  phpmyadmin:
    build: https://github.com/devite-io/phpmyadmin-dockerized.git#main
    restart: always
    environment:
      PMA_HOST: "database"
      PMA_USER: "root"
      PMA_PASSWORD: "${DB_PASSWORD:-password}"
    ports:
      - "8080:80"
    volumes:
      - sw6-phpmyadmin-config:/etc/phpmyadmin:rw
    networks: [sw6-network]
    depends_on:
      database:
        condition: service_healthy

networks:
  sw6-network:
    driver: bridge

volumes:
  sw6-shopware-data:
  sw6-opensearch-data:
  sw6-database-data:
  sw6-phpmyadmin-config: